name: CI
on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Nextflow
        run: |
          curl -s https://get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/nextflow
      - name: Install Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          create-args: >-
            -f nextflow/environment/qc.yml
      - name: Synthetic data
        run: bash tests/data/make_reads.sh tests/data/reads
      - name: Run pipeline with Conda
        shell: bash -l {0}
        run: |
          nextflow run . -profile test,conda \
            --reads "tests/data/reads/*.fastq.gz" \
            --outdir results
      - name: Check outputs
        run: |
          test -s results/qc/fastqc/sampleA_R1_fastqc.html
          test -s results/qc/multiqc/multiqc_report.html
